### PR TITLE
Autozones

### PR DESCRIPTION
**Pull request by the133448**
auto zoning will automatically attempt to find edges of the block you are standing in. It is pretty effective

### CODE REVIEW

**Comment by M-archand** [comment]
@nikooo777 Would you be able to merge this request into a test branch like you did with pr-66 merging? Would be nice to be able to test it out :)

**Comment by the133448** [comment]
@M-archand You can just test it out on https://github.com/the133448/ckSurf/tree/Autozones

But heres a preview of it




_if github preview doesnt load: https://i.imgur.com/FRRaoi5.gif_

**Comment by M-archand** [comment]
Ahh ok, not familiar with github tbh, thanks!

**Comment by the133448** [comment]
@M-archand All g. Let me know what you think of it.

**Comment by M-archand** [comment]
@the133448 The auto-zoning is great man! ck's zoning is pretty awful compared to some other timers, this is a great step. My only suggestion is that you make the default auto height a little bit taller, with height at 50 you can start the timer while jumping in the start zone which annoys some people. I'd say 70+ units since the max jump height is like 66 or something iirc. Might be nice to have different auto heights based on zone type as well, so you could set a taller end zone, etc.

The StealthRevive.inc dependency is missing from your fork btw.

**Comment by the133448** [comment]
Cool. Ill make the autozone height a cvar. And Ill add that dependecnay

**Comment by the133448** [comment]
@M-archand  ck_autozone_height will set the auto zone height

**Comment by M-archand** [comment]
7eb7b64 & c276d76 gives me the following and won't compile.
 ```
// ckSurf/sql.sp(1763) : error 035: argument type mismatch (argument 5)
// ckSurf/surfzones.sp(1895) : error 017: undefined symbol "g_hAutoZoneHeight"
```

**Comment by the133448** [comment]
@M-archand Fixed in 
c6008af

**Comment by M-archand** [comment]
@the133448 really great features/fixes you've been adding in recently my man, keep up the good work! :)

**Comment by M-archand** [comment]
@the133448 I have a comment about your !at feature, I'm not sure which commit it came in. If a map isn't already in the ck_maptier database table it won't create a new one for me despite my server using having full db access. I get this: 
image

However, I have no issue if it's already there and I want to change the tier.

Same issues with !maps for b75acaf

**Comment by the133448** [comment]
@M-archand thats really quite weird.... all !at does, it utilise the !amt command but specify 0 as the zongegroup. Ill have a look at it. As well with the !maps command, I need to do some testing with it. On my server the length of the query is worrying and doesnt justify the means. Im thinking of recreating it to cache the results of that on map load, because those should not change, desipte editing tiers. Ill work on this tonight. Thanks for the feedback.

**Comment by nikooo777** [comment]
sorry guys i've been out of the loop for a while, what would you suggest I do?

**Comment by M-archand** [comment]
I've been using these changes for about 3 weeks now on 2 servers. Pretty great features in my opinion and I haven't ran into any bugs with them yet. Personally I think you should merge :)

**Comment by alerad** [comment]
What's the status on this? Is it only square zones atm?

**Comment by nikooo777** [comment]
I'm closing this PR as my fork is no longer maintained. there are better versions out there now :)

**Pull request closed without merging**
