### PR TITLE
PR For Update 1.19

### PR DESCRIPTION
**Pull request by the133448**

### CODE REVIEW

**Comment by 2called-chaos** [comment]
@nikooo777 I was waiting a bit on this getting merged but I haven't noticed that it's almost only whitespace changes. But I do have to say that I would appreciate if you could cleanup all the files once because my editor strips trailing whitespaces and I suppose I'm not the only one disliking lines with just whitespaces in them.

I currently have to work on my "cleaned" base, and backport the changes to the master so that my changes don't have tons of whitespace changes in them. I can create a PR for current master just for whitespace removal if you want, I just have to open/save all the files once.

But all in all I can work with that since I could easily automate this to get a cleaned master but I think no one would say "hey where are my whitespaces" :D

**Comment by nikooo777** [comment]
hey @2called-chaos 

I would suggest checking out gitkraken, it supposedly handles these issues already. it's worth trying.

I'm deeply sorry for my lack of interaction, I changed job and all in all I've been having little time to play around with cksurf.

Hopefully I can merge ASAP

**Comment by 2called-chaos** [comment]
@nikooo777 No problem, take your time. I just realized that Sourcetree can hide whitespace changes as well, Gitkraken is definitely not my taste of UI design :D So thats basically not a problem anymore.

**Comment by the133448** [comment]
@2called-chaos this is a commit of a version which has the whitespace fixes. I just uploaded niko's repo and commited all of max's changes to it. https://github.com/the133448/CkSurfTest/commit/1d296e9275b471d71c0c64d6d001a6f4cb5c3e53 line 246-286 of hooks.sp is a custom addon for my server. Should never of made it to the commit code.

**Pull request merged**
