### PR TITLE
Minor fixes and updates

### PR DESCRIPTION
**Pull request by Maxximou5**
Minor fixes and updates
Fixed: Missing syntax in admin.sp
Fixed: Replaced %c with proper syntax in ckSurf.phrases.txt
Updated: Commented out deprecated convars in map_types/*.cfg
Updated: Includes to the latest available versions

### CODE REVIEW

**Comment by nikooo777** [comment]
Thank you! I'll look into this in the weekend :)

**Comment by Maxximou5** [comment]
You're welcome! Thanks for keeping it updated, so I figured I would do what I can to help since I am using it.

P.s. I added you on Steam.

**Comment by Destinyg133** [comment]
great job both of you, and i have to ask you, before our loved author of cksurf gets back, would be great if someone who knows how to fix/add new stuff to cksurf, to make ot better, it would be great if you two work together to.make cksurf shine again, also should i update from 1.18 to 1.19?

**Comment by nikooo777** [comment]
great job! i merged it. I'll test it now.

also @Destinyg133 yes i would suggest upgrading.

**Pull request merged**
